CREATE TABLE [dbo].[category](
	[category_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](20) NOT NULL,
	[parent] [int] NULL,
 CONSTRAINT [PK_category] PRIMARY KEY CLUSTERED 
(
	[category_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

INSERT INTO category VALUES('ELECTRONICS',NULL),('TELEVISIONS',1),('TUBE',2),
        ('LCD',2),('PLASMA',2),('PORTABLE ELECTRONICS',1),('MP3 PLAYERS',6),('FLASH',7),
        ('CD PLAYERS',6),('2 WAY RADIOS',6);
GO

